baseURL = "https://releases-qa.aspose.com"

languageCode = "en-us"
title = "Releases - aspose.com"
theme =  "downloads-common-theme"
disableKinds = ["taxonomy", "taxonomyTerm"]
ignoreErrors = ["error-disable-taxonomy"]

################################# Localization #########################
# Disabled languages
disableLanguages = []
defaultContentLang = 'en'
[languages]
    [languages.en]
      contentDir = 'content/en'
      languageName = "English"
      languageCode = "en"
      flag = "flag-us"
      weight = 1
      menuCode = "aspose-en"
    [languages.zh]
      contentDir = 'content/zh'
      languageName = "简体中文"
      languageCode = "zh"
      flag = "flag-cn"
      weight = 5
      menuCode = "aspose-zh"
################################# Localization #########################

[params]
    # googleAnalytics = ""
    # googletagmanager = ""
     backendURL = "https://releases.admin.aspose.com"
     dynamicmenuid = "aspose-en"
     faviconfolder = "aspose"
     contentsection = "com"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
[outputs]
  home= ["HTML", "JSON"]
