# This is a basic workflow to help you get started with Actions

name: Staginghomepage
    
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the mentioned branches
  push:
    branches: [ main1 ]
    paths:
       - 'content/**'
  pull_request:
    branches: [ main1 ]

  repository_dispatch:
    types: [build-homepage]
    
  # Allows the workflow run manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: 'latest'
          extended: true

    - name: Make Content folder for HomePage
      run: |
     
        echo " ========= content BEFORE ===========";
        ls -all;
        echo " ========= content BEFORE ===========";
        ls content -all;
        echo " ========= content zh BEFORE ===========";
        ls content/zh -all;
        
        cp -R content content_new;
        rm -R content;
        mkdir content;
    
        if [ -d "./content_new/en" ]; then
        mkdir content/en;
        cp content_new/en/_index.md content/en;
        fi
        if [ -d "./content_new/zh" ]; then
        mkdir content/zh;
        cp content_new/zh/_index.md content/zh;
        fi
        echo " ========= all AFTER ===========";
        ls -all;
        echo " ========= content AFTER ===========";
        ls content -all;
        echo " ========= content zh AFTER ===========";
        ls content/zh -all;
        

