# This is a basic workflow to help you get started with Actions

name: Staginghomepage
    
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the mentioned branches
  push:
    branches: [ main1 ]
    paths:
       - 'content/**'
  pull_request:
    branches: [ main1 ]

  repository_dispatch:
    types: [build-homepage]
    
  # Allows the workflow run manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: 'latest'
          extended: true

    - name: Make Content folder for HomePage
      run: |
        
        ls content/zh -all;
        
        cp -R content content_new;
        rm -R content;
        mkdir content;
        
        if [ -d "./content_new/de" ]; then
        cp content_new/de/_index.md content/de/;
        fi
        if [ -d "./content_new/el" ]; then
        cp content_new/el/_index.md content/el/;
        fi
        if [ -d "./content_new/en" ]; then
        cp content_new/en/_index.md content/en/;
        fi
        if [ -d "./content_new/es" ]; then
        cp content_new/es/_index.md content/es/;
        fi
        if [ -d "./content_new/fr" ]; then
        cp content_new/fr/_index.md content/fr/;
        fi
        if [ -d "./content_new/id" ]; then
        cp content_new/id/_index.md content/id/;
        fi
        if [ -d "./content_new/ja" ]; then
        cp content_new/ja/_index.md content/ja/;
        fi
        if [ -d "./content_new/pt" ]; then
        cp content_new/pt/_index.md content/pt/;
        fi
        if [ -d "./content_new/ru" ]; then
        cp content_new/ru/_index.md content/ru/;
        fi
        if [ -d "./content_new/tr" ]; then
        cp content_new/tr/_index.md content/tr/;
        fi
        if [ -d "./content_new/zh" ]; then
        cp content_new/zh/_index.md content/zh/;
        fi
        
        ls content -all;
        
        ls content/en -all;
        
        ls content/zh -all;
