# This is a basic workflow to help you get started with Actions

name: Staginghomepage
    
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the mentioned branches
  push:
    branches: [ main1 ]
    paths:
       - 'content/**'
  pull_request:
    branches: [ main1 ]

  repository_dispatch:
    types: [build-homepage]
    
  # Allows the workflow run manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: 'latest'
          extended: true

    - name: Make Content folder for HomePage
      run: |
        cp -R content content_new;
        rm -R content;
        mkdir content;
        
        cp content_new/de/_index.md content;
        cp content_new/el/_index.md content;
        cp content_new/en/_index.md content;
        cp content_new/es/_index.md content;
        cp content_new/fr/_index.md content;
        cp content_new/id/_index.md content;
        cp content_new/ja/_index.md content;
        cp content_new/pt/_index.md content;
        cp content_new/ru/_index.md content;
        cp content_new/tr/_index.md content;
        cp content_new/zh/_index.md content;
        
        ls content -all;
