# This is a basic workflow to help you get started with Actions

name: StagingTotal
    
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the mentioned branches
  push:
    branches: [ main1 ]
    paths:
       - 'content/**'
  pull_request:
    branches: [ main1 ]

  repository_dispatch:
    types: [build-total]
    
  # Allows the workflow run manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: 'latest'
          extended: true

    - name: Remove unwanted folders
      run: |
        find ./content/de -mindepth 1 ! -regex '^./content/de/total\(/.*\)?' -delete
        find ./content/el -mindepth 1 ! -regex '^./content/el/total\(/.*\)?' -delete
        find ./content/en -mindepth 1 ! -regex '^./content/en/total\(/.*\)?' -delete
        find ./content/es -mindepth 1 ! -regex '^./content/es/total\(/.*\)?' -delete
        find ./content/fr -mindepth 1 ! -regex '^./content/fr/total\(/.*\)?' -delete
        find ./content/id -mindepth 1 ! -regex '^./content/id/total\(/.*\)?' -delete
        find ./content/ja -mindepth 1 ! -regex '^./content/ja/total\(/.*\)?' -delete
        find ./content/pt -mindepth 1 ! -regex '^./content/pt/total\(/.*\)?' -delete
        find ./content/ru -mindepth 1 ! -regex '^./content/ru/total\(/.*\)?' -delete
        find ./content/tr -mindepth 1 ! -regex '^./content/tr/total\(/.*\)?' -delete
        find ./content/zh -mindepth 1 ! -regex '^./content/zh/total\(/.*\)?' -delete
        echo " ===== total ===== "
        ls content/ -all;
        echo " ===== total-zh ===== "
        ls content/zh -all;
        echo " ===== total-en ===== "
        ls content/en -all;
        
